# Generated by Django 3.2.16 on 2022-11-17 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0002_auto_20221117_0400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='komentar',
        ),
        migrations.AddField(
            model_name='blog',
            name='Komentar',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='BLOG.komentar'),
        ),
    ]
