# Generated by Django 3.2.16 on 2022-11-17 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0004_alter_blog_komentar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Komentar',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='BLOG.komentar'),
        ),
    ]
