# Generated by Django 3.2.16 on 2022-11-17 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0005_alter_blog_komentar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='Komentar',
        ),
        migrations.AddField(
            model_name='blog',
            name='komentar',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Komentar', to='BLOG.komentar'),
        ),
    ]
