# Generated by Django 3.2.16 on 2022-11-17 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0006_auto_20221117_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='komentar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Komentar', to='BLOG.komentar'),
        ),
    ]
