# Generated by Django 3.2.16 on 2022-11-17 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0007_alter_blog_komentar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='komentar',
            field=models.ForeignKey(default='Null', on_delete=django.db.models.deletion.CASCADE, related_name='Komentar', to='BLOG.komentar'),
        ),
        migrations.AlterField(
            model_name='komentar',
            name='Nik',
            field=models.CharField(default='Null', max_length=64),
        ),
        migrations.AlterField(
            model_name='komentar',
            name='komentar',
            field=models.CharField(default='Null', max_length=64),
        ),
        migrations.AlterField(
            model_name='komentar',
            name='vrijeme_komentara',
            field=models.TimeField(default='Null'),
        ),
    ]
