# Generated by Django 3.2.16 on 2022-11-17 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0008_auto_20221117_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komentar',
            name='Nik',
            field=models.CharField(default=0, max_length=64),
        ),
        migrations.AlterField(
            model_name='komentar',
            name='komentar',
            field=models.CharField(default=0, max_length=64),
        ),
        migrations.AlterField(
            model_name='komentar',
            name='vrijeme_komentara',
            field=models.TimeField(default=0),
        ),
    ]
