# Generated by Django 3.2.16 on 2022-11-17 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0009_auto_20221117_0429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='komentar',
        ),
        migrations.AddField(
            model_name='blog',
            name='komentar',
            field=models.ManyToManyField(blank=True, related_name='Kometar', to='BLOG.Komentar'),
        ),
    ]
