# Generated by Django 3.2.16 on 2022-11-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0010_auto_20221117_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='komentar',
            name='email',
            field=models.EmailField(default=0, max_length=54),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tekst',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='komentar',
            name='vrijeme_komentara',
            field=models.DateField(default=0),
        ),
    ]
