# Generated by Django 3.2.16 on 2022-11-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0011_auto_20221117_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='adresa_slike',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
