# Generated by Django 3.2.16 on 2022-11-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0012_blog_adresa_slike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='adresa_slike',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
