# Generated by Django 3.2.16 on 2022-11-20 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0013_alter_blog_adresa_slike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='komentar',
        ),
        migrations.AddField(
            model_name='blog',
            name='komentar',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Kometar', to='BLOG.komentar'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='komentar',
            name='Nik',
            field=models.CharField(default='NULL', max_length=64),
        ),
        migrations.AlterField(
            model_name='komentar',
            name='email',
            field=models.EmailField(default='NULL', max_length=54),
        ),
        migrations.AlterField(
            model_name='komentar',
            name='komentar',
            field=models.CharField(default='NULL', max_length=64),
        ),
        migrations.AlterField(
            model_name='komentar',
            name='vrijeme_komentara',
            field=models.DateField(default='NULL'),
        ),
    ]
