# Generated by Django 3.2.16 on 2022-11-21 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0014_auto_20221120_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='komentar',
        ),
        migrations.AddField(
            model_name='komentar',
            name='blog',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='BLOG.blog'),
            preserve_default=False,
        ),
    ]
